[workspace]
members = ["app", "cfg", "gui", "pdf", "templates", "tools/age", "tools/rut", "tools/string_extras", "tools/time_utils"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
askama = "0.16.0"
eframe = "0.34.2"
thiserror = "2.0.18"
jiff = "0.2.24"
