[package]
name = "gui"
version.workspace = true
edition.workspace = true

[dependencies]
eframe = { workspace = true }
jiff = { workspace = true }
pdf = { path = "../pdf" }
rfd = "0.17.2"
rut = { path = "../tools/rut" }
templates = { path = "../templates" }
thiserror = { workspace = true }
time_utils = { path = "../tools/time_utils" }
