[package]
name = "templates"
version.workspace = true
edition.workspace = true

[dependencies]
age = { path = "../tools/age" }
askama = { workspace = true }
cfg = { path = "../cfg" }
pdf = { path = "../pdf" }
rut = { path = "../tools/rut" }
thiserror = { workspace = true }
jiff = { workspace = true, features = ["std"] }
time_utils = { path = "../tools/time_utils" }
